# Generated by Django 4.2.5 on 2023-09-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Full name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Experience')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studycenter', verbose_name='Study center')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Full name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone number')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studycenter', verbose_name='Study center')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.teacher', verbose_name='Teacher')),
            ],
        ),
    ]
